// <auto-generated />
namespace Webhelp.Rh.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class IncludeVacancyTechnologyEntity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IncludeVacancyTechnologyEntity));
        
        string IMigrationMetadata.Id
        {
            get { return "202306090159335_IncludeVacancyTechnologyEntity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
